### ISSUE TITLE
イベント編集画面のエラーメッセージの色

### ISSUE THREAD

**Issue by T-Kiyama** [sen-newface/msm-yeahcheese#179]
イベント編集画面のエラーメッセージの色が黒色でわかりづらい気がします。
以下のbootstrapとかを使ってよりいい感じにできそうな気がします！
https://webnetamemo.com/coding/bootstrap/201702264279

**Comment by MinamiKaori** [comment]
updateの表示をすべてまだいじってないのでそのときに合わせて変更します
