### ISSUE TITLE
[fix-認証キー入力]イベントが存在しているか確認

### ISSUE THREAD

**Issue by MinamiKaori** [sen-newface/msm-yeahcheese#86]
- イベント表示画面でイベントが存在しているか確認しているのを認証キー入力画面で確認するようにする

**Comment by MinamiKaori** [comment]
イベントがなかった場合、イベントが見つかりませんでした表示がイベント表示のときに出るようになりました

**Comment by kei-s16** [comment]
たぶんもうやらないのでクローズします
